In [27]:
import numpy as np
import matplotlib.pyplot as plt
import os
import cv2
import glob
import seaborn as sns
from PIL import Image
import glob
import tensorflow as tf
os.environ['CUDA_VISIBLE_DEVICES']='2'
%matplotlib inline

In [28]:
dataDir = '/data/jupyter/libin713/sample_IDCard'
print(len(os.listdir(dataDir + "/original/")))  #380
print(len(os.listdir(dataDir + "/black/")))     #325
print(len(os.listdir(dataDir + "/coloful/")))   #630

380
325
630


In [29]:
ratio = int(0.7*len(os.listdir('/data/jupyter/libin713/sample_IDCard/original')))
os.listdir('/data/jupyter/libin713/sample_IDCard/original')[266:]

['IMG_20190521_112747.jpg',
 'IMG_0582.JPG',
 'IMG_20190521_112849_2.jpg',
 'IMG_0638.JPG',
 'IMG_0515.JPG',
 'IMG_0538.JPG',
 'IMG_0549.JPG',
 'IMG_0526.JPG',
 'IMG_0618.JPG',
 'IMG_20190521_112750_3.jpg',
 'IMG_20190521_112759_1.jpg',
 'IMG_20190521_112713.jpg',
 'IMG_20190521_112806_1.jpg',
 'IMG_20190521_112849_1.jpg',
 'IMG_20190521_112657_1.jpg',
 'IMG_20190521_112740.jpg',
 'IMG_20190521_112759_2.jpg',
 'IMG_0623.JPG',
 'IMG_20190521_112751.jpg',
 'IMG_0530.JPG',
 'IMG_20190521_112759.jpg',
 'IMG_20190521_112837.jpg',
 'IMG_20190521_112727.jpg',
 'IMG_20190521_112858.jpg',
 'IMG_20190521_112918.jpg',
 'IMG_0617.JPG',
 'IMG_0654.JPG',
 'IMG_0508.JPG',
 'IMG_0544.JPG',
 'IMG_0558.JPG',
 'IMG_0588.JPG',
 'IMG_0629.JPG',
 'IMG_0504.JPG',
 'IMG_0503.JPG',
 'IMG_0613.JPG',
 'IMG_0559.JPG',
 'IMG_20190521_112841_1.jpg',
 'IMG_20190521_112927_1.jpg',
 'IMG_0556.JPG',
 'IMG_20190521_112803.jpg',
 'IMG_20190521_112853.jpg',
 'IMG_20190521_112708_1.jpg',
 'IMG_20190521_112807.jpg',
 'IMG_0

In [33]:
#制作训练集  1134张图片
classes = {'original','black','coloful'}  #图像的类别
writer = tf.python_io.TFRecordWriter("Idcard_train1.tfrecords")

for index, name in enumerate(classes):
    class_path = dataDir + "/" + name + "/"
    ratio = int(len(os.listdir(class_path))*0.85)
    print(ratio)
    for img_name in os.listdir(class_path)[:ratio]:
        img_path = class_path + img_name
        if not os.path.isfile(img_path):
            continue
        img = Image.open(img_path)
        img = img.resize((600,600))
        img_raw = img.tobytes()
        example = tf.train.Example(features = tf.train.Features(feature = {
            "label":tf.train.Feature(int64_list = tf.train.Int64List(value = [index])),
            'img_raw':tf.train.Feature(bytes_list = tf.train.BytesList(value = [img_raw]))
        }))
        writer.write(example.SerializeToString())  #序列化为字符串
writer.close()



535
276
323


In [35]:
535+276+323

1134

In [34]:
##制作测试集  201张
classes = {'original','black','coloful'}  #图像的类别
writer = tf.python_io.TFRecordWriter("Idcard_test1.tfrecords")

for index, name in enumerate(classes):
    class_path = dataDir + "/" + name + "/"
    ratio = int(len(os.listdir(class_path))*0.85)
    print(len(os.listdir(class_path))-ratio)
    for img_name in os.listdir(class_path)[ratio:]:
        img_path = class_path + img_name
        if not os.path.isfile(img_path):
            continue
        img = Image.open(img_path)
        img = img.resize((600,600))
        img_raw = img.tobytes()
        example = tf.train.Example(features = tf.train.Features(feature = {
            "label":tf.train.Feature(int64_list = tf.train.Int64List(value = [index])),
            'img_raw':tf.train.Feature(bytes_list = tf.train.BytesList(value = [img_raw]))
        }))
        writer.write(example.SerializeToString())  #序列化为字符串
writer.close()
            

95
49
57


In [36]:
95+49+57

201

In [37]:
#观察图片数据[1 0 0]彩色图 [0 1 0] 黑白图  [0 0 1]原件
filename_queue = tf.train.string_input_producer(["Idcard_train1.tfrecords"])  # 读入流中
reader = tf.TFRecordReader()
_, serialized_example = reader.read(filename_queue)  # 返回文件名和文件
features = tf.parse_single_example(serialized_example,
                                   features={
                                       'label': tf.FixedLenFeature([], tf.int64),
                                       'img_raw': tf.FixedLenFeature([], tf.string),
                                   })  # 取出包含image和label的feature对象
image = tf.decode_raw(features['img_raw'], tf.uint8)
image = tf.reshape(image, [600, 600, 3])
label = tf.cast(features['label'], tf.int32)
label = tf.one_hot(label, 3, 1, 0)
with tf.Session() as sess:  # 开始一个会话
    init_op = tf.initialize_all_variables()
    sess.run(init_op)
    coord = tf.train.Coordinator()
    threads = tf.train.start_queue_runners(coord=coord)
    for i in range(800):
        example, l = sess.run([image, label])  # 在会话中取出image和label
        print("%%%%%:",l)
        print("\n")
        img = Image.fromarray(example, 'RGB')  # 这里Image是之前提到的
        img.save(dataDir +'/test1/'+ str(i) + '_''Label_' + str(l) + '.jpg')  # 存下图片
        print(example, l)
    coord.request_stop()
    coord.join(threads)


Instructions for updating:
Use `tf.global_variables_initializer` instead.
%%%%%: [1 0 0]


[[[50 49 44]
  [42 43 37]
  [44 43 38]
  ...
  [27 29 28]
  [21 21 19]
  [29 27 28]]

 [[51 50 46]
  [50 51 45]
  [51 50 46]
  ...
  [25 27 24]
  [32 32 30]
  [33 32 30]]

 [[48 49 44]
  [41 40 36]
  [41 42 37]
  ...
  [35 35 33]
  [21 23 22]
  [34 35 30]]

 ...

 [[50 45 39]
  [53 46 40]
  [53 46 40]
  ...
  [27 22 19]
  [28 23 19]
  [32 27 23]]

 [[55 51 42]
  [55 50 44]
  [55 48 42]
  ...
  [30 25 19]
  [23 20 13]
  [28 21 15]]

 [[54 47 41]
  [48 41 35]
  [51 46 40]
  ...
  [29 21 18]
  [29 20 15]
  [27 24 19]]] [1 0 0]
%%%%%: [1 0 0]


[[[37 34 29]
  [36 35 31]
  [36 33 28]
  ...
  [33 34 29]
  [26 30 29]
  [29 31 28]]

 [[32 31 26]
  [41 40 38]
  [41 37 34]
  ...
  [21 22 17]
  [26 31 27]
  [21 23 20]]

 [[51 48 39]
  [89 88 83]
  [33 29 28]
  ...
  [22 23 18]
  [27 29 26]
  [30 30 28]]

 ...

 [[45 41 38]
  [41 37 36]
  [34 34 32]
  ...
  [ 8  8  6]
  [ 8  8  6]
  [11 13 10]]

 [[42 34 32]

[[[ 71  82  78]
  [ 66  77  71]
  [ 75  75  73]
  ...
  [ 15  16  11]
  [ 14  16  13]
  [ 13  15  12]]

 [[ 72  78  74]
  [ 73  78  74]
  [ 70  79  74]
  ...
  [ 14  15  10]
  [ 17  19  16]
  [ 15  17  14]]

 [[ 71  73  72]
  [ 72  78  76]
  [ 71  77  73]
  ...
  [ 12  14   9]
  [ 12  14  11]
  [ 12  14   9]]

 ...

 [[119  73  73]
  [124  81  65]
  [121  76  57]
  ...
  [ 19  19  17]
  [ 25  25  23]
  [ 19  19  17]]

 [[127  77  66]
  [125  78  62]
  [125  78  60]
  ...
  [ 16  16  14]
  [ 14  16  13]
  [ 17  19  16]]

 [[133  84  77]
  [126  81  62]
  [121  79  57]
  ...
  [ 18  20  17]
  [ 14  16  13]
  [ 15  17  14]]] [1 0 0]
%%%%%: [1 0 0]


[[[ 44  40  28]
  [ 37  37  27]
  [ 39  36  27]
  ...
  [ 52  46  34]
  [ 58  52  38]
  [ 60  53  43]]

 [[ 39  40  26]
  [ 36  36  26]
  [ 40  40  30]
  ...
  [ 54  48  36]
  [ 54  48  34]
  [ 57  51  39]]

 [[ 39  36  27]
  [ 35  35  25]
  [ 34  34  24]
  ...
  [ 57  51  39]
  [ 60  57  42]
  [ 55  52  37]]

 ...

 [[177 111  77]
  [182 115 

[[[53 53 45]
  [35 36 31]
  [44 43 39]
  ...
  [23 23 21]
  [22 22 20]
  [30 27 22]]

 [[44 43 39]
  [44 44 42]
  [39 38 36]
  ...
  [23 22 20]
  [14 14 14]
  [30 26 23]]

 [[46 45 43]
  [45 44 42]
  [45 44 42]
  ...
  [23 23 21]
  [17 17 17]
  [40 39 35]]

 ...

 [[54 47 41]
  [44 37 31]
  [48 44 35]
  ...
  [26 21 18]
  [25 17 14]
  [23 18 14]]

 [[55 48 40]
  [47 43 34]
  [46 42 33]
  ...
  [24 19 15]
  [27 24 17]
  [40 31 26]]

 [[51 46 40]
  [51 46 40]
  [46 39 33]
  ...
  [28 25 18]
  [26 23 16]
  [28 21 15]]] [1 0 0]
%%%%%: [1 0 0]


[[[221 206 173]
  [221 207 172]
  [219 206 171]
  ...
  [229 217 179]
  [229 216 181]
  [229 218 188]]

 [[220 207 173]
  [217 204 169]
  [221 207 172]
  ...
  [229 217 179]
  [233 220 185]
  [233 221 183]]

 [[220 207 173]
  [221 208 173]
  [221 207 172]
  ...
  [232 219 184]
  [229 216 181]
  [228 215 180]]

 ...

 [[211 196 157]
  [210 195 156]
  [205 190 151]
  ...
  [173 155 117]
  [176 158 118]
  [175 157 117]]

 [[212 195 152]
  [211 193 155]

[[[225  70  52]
  [222  69  53]
  [229  73  60]
  ...
  [198  51  33]
  [196  51  32]
  [197  52  33]]

 [[227  75  54]
  [227  75  54]
  [225  72  54]
  ...
  [201  54  36]
  [201  54  36]
  [204  57  37]]

 [[228  76  62]
  [228  77  56]
  [232  81  60]
  ...
  [198  51  35]
  [200  53  37]
  [202  55  39]]

 ...

 [[232 164 155]
  [231 163 152]
  [223 155 142]
  ...
  [184  47  28]
  [189  44  27]
  [187  40  22]]

 [[232 164 151]
  [230 163 147]
  [228 160 147]
  ...
  [191  52  31]
  [188  46  24]
  [187  40  22]]

 [[228 160 149]
  [223 153 141]
  [229 160 145]
  ...
  [184  43  25]
  [190  42  32]
  [190  42  28]]] [1 0 0]
%%%%%: [1 0 0]


[[[226  68  56]
  [225  75  61]
  [221  69  56]
  ...
  [201  48  34]
  [201  48  32]
  [203  53  29]]

 [[231  81  64]
  [228  77  56]
  [224  73  56]
  ...
  [197  46  29]
  [198  45  29]
  [194  41  25]]

 [[231  82  62]
  [226  76  59]
  [227  76  57]
  ...
  [204  53  34]
  [203  50  32]
  [200  47  31]]

 ...

 [[218 130 120]
  [218 131 

[[[78 78 70]
  [78 76 64]
  [73 73 63]
  ...
  [53 54 49]
  [56 57 49]
  [53 54 46]]

 [[76 73 64]
  [77 77 67]
  [79 76 67]
  ...
  [56 57 51]
  [60 61 53]
  [55 56 48]]

 [[71 71 61]
  [76 76 66]
  [73 69 60]
  ...
  [59 60 52]
  [52 53 45]
  [59 60 52]]

 ...

 [[77 76 71]
  [75 76 71]
  [79 78 73]
  ...
  [17 19 18]
  [20 22 21]
  [16 16 16]]

 [[73 72 68]
  [66 67 62]
  [74 74 72]
  ...
  [20 22 21]
  [14 16 15]
  [16 16 16]]

 [[78 77 73]
  [80 80 78]
  [78 79 73]
  ...
  [19 21 20]
  [12 14 13]
  [18 18 18]]] [1 0 0]
%%%%%: [1 0 0]


[[[ 27  28  22]
  [ 26  28  17]
  [ 25  27  16]
  ...
  [ 49  43  31]
  [ 52  44  31]
  [ 46  40  26]]

 [[ 28  30  19]
  [ 25  27  14]
  [ 28  30  19]
  ...
  [ 51  45  33]
  [ 48  42  28]
  [ 45  41  29]]

 [[ 28  28  18]
  [ 28  30  19]
  [ 25  27  16]
  ...
  [ 49  41  30]
  [ 47  44  29]
  [ 47  48  34]]

 ...

 [[154  79  40]
  [153  84  43]
  [162  93  52]
  ...
  [  8   9   4]
  [ 10  11   6]
  [ 10   9   5]]

 [[157  83  48]
  [157  89  44]

[[[77 74 69]
  [73 72 67]
  [74 75 67]
  ...
  [64 65 57]
  [65 67 56]
  [63 61 64]]

 [[79 78 73]
  [76 75 70]
  [69 68 63]
  ...
  [66 67 59]
  [59 60 52]
  [64 62 63]]

 [[78 75 70]
  [72 71 67]
  [72 71 66]
  ...
  [64 63 58]
  [65 65 57]
  [55 55 55]]

 ...

 [[87 86 84]
  [85 85 83]
  [80 81 76]
  ...
  [25 25 23]
  [26 26 24]
  [20 20 18]]

 [[85 84 82]
  [80 80 78]
  [81 82 77]
  ...
  [22 24 21]
  [24 24 24]
  [27 27 25]]

 [[85 83 84]
  [80 80 78]
  [80 79 77]
  ...
  [26 26 24]
  [24 24 24]
  [25 27 22]]] [1 0 0]
%%%%%: [1 0 0]


[[[199  43  30]
  [195  39  26]
  [198  42  27]
  ...
  [145  22   7]
  [143  21   6]
  [144  22   9]]

 [[199  43  30]
  [198  42  29]
  [202  46  31]
  ...
  [144  22   7]
  [142  20   5]
  [149  27  14]]

 [[199  41  29]
  [196  38  26]
  [196  40  27]
  ...
  [137  15   0]
  [145  23   8]
  [145  23  10]]

 ...

 [[255 106  81]
  [255 105  81]
  [255 107  83]
  ...
  [210  55  35]
  [207  52  34]
  [208  53  35]]

 [[255 106  81]
  [254 105  81]

%%%%%: [1 0 0]


[[[195  50  33]
  [196  51  34]
  [194  47  29]
  ...
  [165  33  21]
  [167  35  22]
  [164  34  21]]

 [[191  49  29]
  [197  55  35]
  [198  53  34]
  ...
  [166  34  22]
  [163  31  18]
  [165  35  19]]

 [[198  50  38]
  [198  53  34]
  [200  55  36]
  ...
  [168  36  23]
  [167  35  20]
  [164  32  20]]

 ...

 [[220 144 118]
  [217 143 116]
  [217 138 108]
  ...
  [159  27  14]
  [157  27  13]
  [162  30  17]]

 [[206 121 100]
  [209 128 101]
  [205 120  99]
  ...
  [156  24  11]
  [159  29  15]
  [158  28  15]]

 [[207 115 100]
  [203 114  96]
  [207 122 101]
  ...
  [156  26  10]
  [157  25  13]
  [160  28  16]]] [1 0 0]
%%%%%: [1 0 0]


[[[189  37  23]
  [192  40  27]
  [185  35  21]
  ...
  [149  26  10]
  [153  30  14]
  [147  21   7]]

 [[194  42  28]
  [193  41  28]
  [193  41  28]
  ...
  [145  22   6]
  [152  29  13]
  [145  19   5]]

 [[190  38  24]
  [189  37  24]
  [194  42  29]
  ...
  [152  29  13]
  [149  26  10]
  [148  22   8]]

 ...

 [[255 126

[[[248 225 175]
  [251 223 175]
  [253 227 178]
  ...
  [239 215 169]
  [243 216 171]
  [242 215 170]]

 [[250 227 177]
  [251 225 176]
  [251 225 176]
  ...
  [238 214 168]
  [238 214 168]
  [240 216 170]]

 [[250 224 175]
  [248 222 173]
  [250 224 175]
  ...
  [241 214 169]
  [241 217 173]
  [245 218 175]]

 ...

 [[ 39  36  29]
  [ 33  32  27]
  [ 35  34  29]
  ...
  [ 32  33  28]
  [ 34  35  29]
  [ 29  32  25]]

 [[ 35  35  25]
  [ 35  32  25]
  [ 39  38  33]
  ...
  [ 35  36  31]
  [ 26  27  22]
  [ 29  30  25]]

 [[ 33  33  25]
  [ 38  37  32]
  [ 32  31  26]
  ...
  [ 29  30  25]
  [ 30  31  25]
  [ 29  30  24]]] [1 0 0]
%%%%%: [1 0 0]


[[[218  68  51]
  [221  71  56]
  [218  71  55]
  ...
  [191  41  26]
  [193  43  28]
  [195  48  30]]

 [[221  71  57]
  [217  67  53]
  [220  70  55]
  ...
  [192  42  27]
  [191  41  26]
  [195  45  31]]

 [[220  70  53]
  [217  67  50]
  [220  73  55]
  ...
  [197  46  29]
  [192  41  24]
  [191  39  25]]

 ...

 [[219 146 137]
  [218 146 

[[[59 55 43]
  [58 51 41]
  [63 54 49]
  ...
  [69 66 57]
  [67 63 52]
  [72 65 55]]

 [[44 35 38]
  [51 44 36]
  [55 49 35]
  ...
  [72 65 55]
  [68 61 51]
  [71 64 54]]

 [[53 44 27]
  [56 50 36]
  [53 47 35]
  ...
  [69 62 52]
  [67 60 50]
  [68 61 51]]

 ...

 [[50 36 23]
  [56 40 25]
  [55 42 26]
  ...
  [19 18 13]
  [18 17 12]
  [20 17 12]]

 [[49 36 19]
  [55 36 21]
  [48 32 16]
  ...
  [16 13  8]
  [16 15 10]
  [11 10  5]]

 [[51 38 22]
  [52 37 14]
  [54 38 25]
  ...
  [16 13  8]
  [18 17 12]
  [13 12  8]]] [1 0 0]
%%%%%: [1 0 0]


[[[118  50  29]
  [107  52  31]
  [111  55  32]
  ...
  [ 45  47  42]
  [ 44  44  36]
  [ 51  47  38]]

 [[112  57  36]
  [107  53  29]
  [110  54  31]
  ...
  [ 48  47  42]
  [ 43  43  33]
  [ 52  48  39]]

 [[ 96  60  38]
  [107  53  29]
  [107  57  34]
  ...
  [ 47  44  35]
  [ 49  49  39]
  [ 49  49  39]]

 ...

 [[ 23  24  19]
  [ 14  15  10]
  [ 13  14   9]
  ...
  [ 21  20  15]
  [ 25  22  15]
  [ 26  23  18]]

 [[  8   7   2]
  [ 12  11   7]

[[[251 221 151]
  [253 223 151]
  [253 223 151]
  ...
  [234 201 132]
  [234 204 132]
  [236 203 132]]

 [[253 222 155]
  [253 223 153]
  [253 223 151]
  ...
  [239 206 137]
  [237 204 133]
  [236 203 132]]

 [[253 222 155]
  [252 222 152]
  [254 221 150]
  ...
  [239 206 135]
  [236 203 132]
  [239 204 136]]

 ...

 [[184 148  86]
  [184 148  88]
  [185 149  89]
  ...
  [190 152  87]
  [185 150  84]
  [191 156  90]]

 [[183 149  88]
  [182 146  86]
  [178 142  82]
  ...
  [189 154  88]
  [190 155  89]
  [188 150  85]]

 [[181 147  86]
  [181 147  86]
  [181 147  86]
  ...
  [184 146  81]
  [183 148  80]
  [187 152  84]]] [1 0 0]
%%%%%: [1 0 0]


[[[35 30 24]
  [42 41 36]
  [34 33 28]
  ...
  [30 29 24]
  [34 34 26]
  [24 25 19]]

 [[48 43 39]
  [45 44 40]
  [34 33 28]
  ...
  [39 38 33]
  [43 43 35]
  [25 27 22]]

 [[46 41 37]
  [51 47 44]
  [45 44 40]
  ...
  [39 39 31]
  [25 26 20]
  [22 24 21]]

 ...

 [[30 32 31]
  [32 34 33]
  [35 35 35]
  ...
  [16 16 14]
  [ 9  9  7]
  [12 10 1

%%%%%: [1 0 0]


[[[41 37 36]
  [39 38 36]
  [22 21 19]
  ...
  [15 20 16]
  [22 26 25]
  [20 24 23]]

 [[38 37 35]
  [43 43 41]
  [37 36 34]
  ...
  [26 28 27]
  [18 20 17]
  [26 28 25]]

 [[38 37 33]
  [35 34 32]
  [36 35 33]
  ...
  [19 23 22]
  [23 23 23]
  [25 27 26]]

 ...

 [[56 52 49]
  [57 54 49]
  [59 56 51]
  ...
  [33 29 28]
  [26 25 23]
  [32 31 29]]

 [[50 47 42]
  [56 53 48]
  [53 52 47]
  ...
  [35 31 30]
  [35 31 28]
  [33 29 26]]

 [[53 48 42]
  [51 46 42]
  [54 53 48]
  ...
  [34 30 29]
  [30 26 23]
  [34 30 27]]] [1 0 0]
%%%%%: [1 0 0]


[[[17 16 12]
  [22 21 16]
  [19 20 15]
  ...
  [79 76 69]
  [74 71 66]
  [92 88 77]]

 [[16 15 11]
  [19 18 14]
  [17 16 11]
  ...
  [78 79 63]
  [77 77 69]
  [74 74 62]]

 [[18 17 13]
  [20 19 15]
  [18 19 14]
  ...
  [81 78 69]
  [82 79 72]
  [82 82 70]]

 ...

 [[64 65 51]
  [59 59 47]
  [64 61 54]
  ...
  [68 65 58]
  [62 59 52]
  [64 64 56]]

 [[60 60 50]
  [58 58 48]
  [65 62 53]
  ...
  [64 64 56]
  [62 63 57]
  [64 65 59]]



[[[10  6  3]
  [14 15 10]
  [19 20 15]
  ...
  [60 57 52]
  [61 58 51]
  [47 50 43]]

 [[16 12  9]
  [16 15 11]
  [21 20 16]
  ...
  [53 53 43]
  [47 47 37]
  [56 56 46]]

 [[22 21 19]
  [19 18 14]
  [23 24 19]
  ...
  [42 39 32]
  [41 38 31]
  [46 46 38]]

 ...

 [[ 7  6  4]
  [ 8  7  5]
  [ 7  6  4]
  ...
  [25 26 18]
  [37 37 29]
  [35 32 25]]

 [[ 8  8  6]
  [ 8  8  6]
  [ 7  7  5]
  ...
  [30 30 22]
  [31 31 23]
  [24 24 16]]

 [[ 6  7  2]
  [ 7  7  5]
  [ 7  7  5]
  ...
  [24 25 17]
  [25 25 17]
  [27 22 16]]] [1 0 0]
%%%%%: [1 0 0]


[[[227 214 182]
  [223 212 180]
  [226 211 180]
  ...
  [238 225 191]
  [237 224 190]
  [237 224 190]]

 [[227 214 182]
  [224 211 179]
  [228 215 183]
  ...
  [236 223 191]
  [235 222 190]
  [236 222 193]]

 [[226 213 181]
  [229 216 184]
  [227 216 184]
  ...
  [237 223 196]
  [235 222 190]
  [236 222 193]]

 ...

 [[207 191 157]
  [208 192 158]
  [209 193 160]
  ...
  [182 163 130]
  [180 161 128]
  [180 162 126]]

 [[208 194 157]
  [205 191 154]

%%%%%: [1 0 0]


[[[211  54  47]
  [212  56  44]
  [218  60  49]
  ...
  [187  39  27]
  [188  37  28]
  [181  30  19]]

 [[220  64  51]
  [214  58  45]
  [216  58  47]
  ...
  [186  40  27]
  [184  37  27]
  [185  38  30]]

 [[209  53  40]
  [214  58  45]
  [221  63  52]
  ...
  [187  41  28]
  [188  42  29]
  [187  41  28]]

 ...

 [[174  30  21]
  [173  31  19]
  [175  31  20]
  ...
  [169  56  42]
  [165  52  36]
  [165  52  34]]

 [[172  28  19]
  [174  30  19]
  [174  32  20]
  ...
  [166  54  40]
  [166  53  37]
  [169  56  40]]

 [[173  31  19]
  [172  30  20]
  [173  31  21]
  ...
  [159  45  34]
  [165  49  36]
  [155  37  25]]] [1 0 0]
%%%%%: [1 0 0]


[[[43 44 36]
  [36 36 26]
  [38 41 30]
  ...
  [16 16  8]
  [ 9 12  5]
  [15 17 14]]

 [[68 65 56]
  [46 46 36]
  [39 40 32]
  ...
  [17 20 11]
  [28 29 23]
  [28 27 22]]

 [[28 27 23]
  [43 45 34]
  [42 42 34]
  ...
  [22 23 17]
  [20 19 14]
  [28 24 21]]

 ...

 [[40 42 41]
  [37 37 35]
  [44 45 40]
  ...
  [14 15 10]
  [ 6 

[[[87 81 65]
  [93 87 71]
  [91 85 73]
  ...
  [73 71 58]
  [72 68 56]
  [75 68 58]]

 [[91 85 71]
  [88 82 68]
  [89 83 71]
  ...
  [75 73 60]
  [76 72 60]
  [75 68 58]]

 [[92 84 71]
  [95 87 74]
  [96 90 78]
  ...
  [73 71 59]
  [72 68 57]
  [72 66 54]]

 ...

 [[57 56 51]
  [60 59 54]
  [58 55 50]
  ...
  [20 23 16]
  [22 25 18]
  [19 22 15]]

 [[59 58 53]
  [57 58 52]
  [52 49 44]
  ...
  [17 19 14]
  [13 18 11]
  [15 22 15]]

 [[59 58 53]
  [62 61 56]
  [56 53 48]
  ...
  [18 20 15]
  [18 23 17]
  [16 22 18]]] [1 0 0]
%%%%%: [1 0 0]


[[[106  51  46]
  [103  51  38]
  [ 95  46  32]
  ...
  [ 30  31  26]
  [ 26  28  25]
  [ 30  32  31]]

 [[ 98  49  35]
  [101  52  37]
  [100  51  36]
  ...
  [ 27  29  24]
  [ 24  29  23]
  [ 27  29  26]]

 [[102  54  44]
  [101  52  37]
  [101  52  37]
  ...
  [ 30  31  26]
  [ 37  38  33]
  [ 30  32  27]]

 ...

 [[ 19  19  17]
  [ 16  16  14]
  [ 13  15  12]
  ...
  [ 28  30  27]
  [ 34  35  30]
  [ 35  31  28]]

 [[ 10  12   9]
  [ 12  14  11]

[[[250 225 171]
  [250 224 173]
  [250 224 173]
  ...
  [232 207 153]
  [226 203 149]
  [229 204 148]]

 [[250 225 171]
  [250 224 173]
  [250 224 173]
  ...
  [230 205 151]
  [233 206 153]
  [229 204 148]]

 [[252 225 172]
  [253 225 175]
  [249 223 172]
  ...
  [231 206 150]
  [231 206 152]
  [226 204 147]]

 ...

 [[204 177 124]
  [204 179 125]
  [206 179 126]
  ...
  [145 123  74]
  [148 124  76]
  [148 122  71]]

 [[205 178 125]
  [201 174 121]
  [204 177 122]
  ...
  [148 124  76]
  [145 121  73]
  [147 121  70]]

 [[201 174 121]
  [202 175 122]
  [204 177 122]
  ...
  [148 124  76]
  [148 125  75]
  [146 119  72]]] [1 0 0]
%%%%%: [1 0 0]


[[[82 80 68]
  [81 79 67]
  [90 86 74]
  ...
  [60 60 50]
  [73 70 63]
  [61 58 51]]

 [[77 75 63]
  [75 73 61]
  [86 84 72]
  ...
  [67 64 57]
  [63 63 55]
  [67 66 62]]

 [[85 82 73]
  [75 73 61]
  [83 80 71]
  ...
  [67 64 59]
  [57 56 51]
  [63 63 61]]

 ...

 [[44 46 43]
  [47 47 45]
  [43 45 42]
  ...
  [25 25 23]
  [21 21 19]
  [15 14 1

[[[249  66  32]
  [250  67  33]
  [250  68  31]
  ...
  [198  28   3]
  [193  23   0]
  [198  29   6]]

 [[248  65  31]
  [250  67  33]
  [255  73  36]
  ...
  [205  35  10]
  [208  38  15]
  [200  30   7]]

 [[251  68  34]
  [253  70  36]
  [247  65  28]
  ...
  [203  34  11]
  [212  42  19]
  [208  36  14]]

 ...

 [[252 126  85]
  [253 128  84]
  [254 127  84]
  ...
  [218  38  11]
  [214  35   5]
  [215  35   8]]

 [[253 130  88]
  [252 127  83]
  [253 126  83]
  ...
  [217  36   9]
  [217  37  12]
  [222  42  15]]

 [[253 126  85]
  [254 127  84]
  [252 125  84]
  ...
  [215  37   9]
  [218  40  12]
  [218  36  14]]] [1 0 0]
%%%%%: [1 0 0]


[[[122  50  36]
  [117  51  35]
  [110  55  35]
  ...
  [ 50  37  31]
  [ 58  43  38]
  [ 45  42  33]]

 [[109  48  29]
  [118  55  37]
  [115  60  39]
  ...
  [ 55  44  38]
  [ 58  45  39]
  [ 48  44  33]]

 [[117  51  39]
  [120  59  40]
  [115  56  38]
  ...
  [ 51  38  32]
  [ 56  43  37]
  [ 55  38  31]]

 ...

 [[  6   5   1]
  [  8   7 

[[[ 95  86  71]
  [100  91  76]
  [101  93  82]
  ...
  [ 76  73  58]
  [ 74  70  58]
  [ 72  68  56]]

 [[ 97  88  73]
  [ 96  87  72]
  [ 95  87  74]
  ...
  [ 75  72  57]
  [ 78  74  62]
  [ 78  74  62]]

 [[106  99  83]
  [ 97  90  74]
  [ 98  91  75]
  ...
  [ 75  72  57]
  [ 74  70  58]
  [ 72  68  57]]

 ...

 [[ 54  53  48]
  [ 64  61  54]
  [ 52  49  44]
  ...
  [ 23  23  21]
  [ 19  18  14]
  [ 17  16  12]]

 [[ 54  51  46]
  [ 51  51  43]
  [ 58  58  50]
  ...
  [ 22  21  17]
  [ 18  17  13]
  [ 20  19  14]]

 [[ 62  59  54]
  [ 55  55  47]
  [ 61  58  51]
  ...
  [ 21  18  13]
  [ 24  23  19]
  [ 20  19  14]]] [1 0 0]
%%%%%: [1 0 0]


[[[17 17 17]
  [14 14 12]
  [25 24 22]
  ...
  [71 71 61]
  [75 72 65]
  [64 64 56]]

 [[17 18 12]
  [18 19 14]
  [19 20 15]
  ...
  [71 71 59]
  [73 71 59]
  [79 76 67]]

 [[16 17 11]
  [13 14  9]
  [18 21 14]
  ...
  [74 69 63]
  [73 70 61]
  [71 68 59]]

 ...

 [[64 61 52]
  [59 59 49]
  [64 59 53]
  ...
  [57 58 52]
  [56 57 52]
  [55 60 5

[[[228  61  42]
  [230  64  42]
  [232  66  44]
  ...
  [191  42  20]
  [183  34  12]
  [190  41  19]]

 [[227  60  41]
  [224  58  36]
  [222  56  34]
  ...
  [183  34  12]
  [185  36  14]
  [180  31   9]]

 [[219  52  33]
  [221  55  33]
  [223  57  35]
  ...
  [187  38  18]
  [184  35  15]
  [185  36  16]]

 ...

 [[249 136 104]
  [252 139 107]
  [251 136 107]
  ...
  [177  28   6]
  [179  33  10]
  [184  35  15]]

 [[252 137 106]
  [254 139 108]
  [251 136 107]
  ...
  [182  36  13]
  [194  48  25]
  [181  34  14]]

 [[251 136 105]
  [253 138 107]
  [252 137 108]
  ...
  [190  44  21]
  [189  40  18]
  [180  31  11]]] [1 0 0]
%%%%%: [1 0 0]


[[[44 45 37]
  [38 44 34]
  [37 43 33]
  ...
  [55 49 37]
  [58 54 43]
  [47 49 36]]

 [[38 41 30]
  [39 45 35]
  [38 41 30]
  ...
  [49 45 33]
  [53 47 35]
  [57 51 39]]

 [[47 43 34]
  [47 47 37]
  [48 50 39]
  ...
  [57 49 38]
  [57 49 38]
  [52 44 33]]

 ...

 [[40 26 15]
  [45 31 22]
  [41 27 16]
  ...
  [10 11  6]
  [10 11  6]
  [11 12  

[[[44 47 38]
  [34 29 23]
  [23 20 13]
  ...
  [21 22 16]
  [31 30 25]
  [29 28 23]]

 [[37 38 30]
  [32 29 24]
  [40 39 34]
  ...
  [25 26 20]
  [24 25 20]
  [27 28 23]]

 [[32 31 26]
  [27 26 21]
  [27 28 22]
  ...
  [26 27 22]
  [28 27 23]
  [31 30 26]]

 ...

 [[41 42 36]
  [34 35 30]
  [34 35 29]
  ...
  [14 14 12]
  [10 10  8]
  [11 10  6]]

 [[28 30 25]
  [29 30 25]
  [34 33 28]
  ...
  [11 11  9]
  [ 7  7  5]
  [10 10  8]]

 [[21 26 22]
  [24 26 21]
  [38 35 30]
  ...
  [ 9 11  8]
  [ 9 10  5]
  [13 13 11]]] [1 0 0]
%%%%%: [1 0 0]


[[[40 39 34]
  [36 35 31]
  [43 39 36]
  ...
  [19 21 18]
  [20 22 19]
  [17 19 14]]

 [[36 35 30]
  [29 28 24]
  [37 33 30]
  ...
  [26 28 25]
  [27 27 25]
  [24 23 19]]

 [[35 34 29]
  [36 35 31]
  [36 35 31]
  ...
  [17 17 15]
  [26 28 25]
  [24 23 19]]

 ...

 [[60 53 45]
  [62 55 49]
  [58 51 45]
  ...
  [23 18 15]
  [22 19 14]
  [24 19 13]]

 [[62 55 47]
  [58 49 44]
  [56 49 43]
  ...
  [27 23 20]
  [29 24 20]
  [28 23 19]]

 [[61 52 45]
  [5

[[[65 51 50]
  [35 38 29]
  [33 34 28]
  ...
  [21 22 16]
  [24 25 19]
  [23 24 18]]

 [[34 33 28]
  [33 34 28]
  [36 36 28]
  ...
  [19 19 17]
  [20 21 15]
  [16 17 11]]

 [[27 26 22]
  [34 33 28]
  [38 37 33]
  ...
  [24 25 19]
  [23 22 17]
  [22 23 18]]

 ...

 [[32 33 28]
  [33 33 31]
  [39 41 36]
  ...
  [ 9 10  5]
  [ 7  9  6]
  [ 7  9  4]]

 [[32 33 28]
  [34 35 30]
  [45 46 41]
  ...
  [11 11  9]
  [ 5  7  4]
  [ 5  7  4]]

 [[32 33 28]
  [38 40 35]
  [41 40 36]
  ...
  [ 6  6  6]
  [ 7  7  5]
  [ 9  9  7]]] [1 0 0]
%%%%%: [1 0 0]


[[[12 16 17]
  [17 19 18]
  [16 18 15]
  ...
  [40 39 37]
  [38 39 34]
  [33 34 29]]

 [[16 18 17]
  [16 18 15]
  [16 18 15]
  ...
  [53 54 49]
  [43 44 38]
  [33 34 29]]

 [[13 17 16]
  [15 17 16]
  [16 18 15]
  ...
  [27 27 25]
  [34 35 30]
  [67 66 62]]

 ...

 [[ 9  9  7]
  [ 8  8  6]
  [ 4  4  2]
  ...
  [17 20 13]
  [23 26 17]
  [31 37 27]]

 [[ 5  5  5]
  [ 6  6  4]
  [ 5  5  3]
  ...
  [19 20 15]
  [24 27 20]
  [25 31 21]]

 [[ 4  4  4]
  [ 

[[[230  50  23]
  [228  48  21]
  [229  51  23]
  ...
  [189  26   9]
  [193  30  13]
  [191  28  11]]

 [[225  45  20]
  [227  49  23]
  [227  49  21]
  ...
  [188  25   8]
  [191  28  11]
  [194  31  14]]

 [[226  48  22]
  [229  51  25]
  [228  50  24]
  ...
  [195  32  15]
  [187  26   6]
  [204  43  23]]

 ...

 [[253 120  85]
  [252 119  84]
  [253 120  87]
  ...
  [196  36  14]
  [194  32   9]
  [187  25   2]]

 [[249 116  81]
  [251 118  85]
  [252 119  86]
  ...
  [195  35  13]
  [198  36  15]
  [198  36  15]]

 [[248 115  82]
  [251 118  85]
  [248 115  82]
  ...
  [199  39  17]
  [189  27   6]
  [199  37  16]]] [1 0 0]
%%%%%: [1 0 0]


[[[13 15 10]
  [14 15  9]
  [11 10  6]
  ...
  [88 85 80]
  [89 84 81]
  [77 71 73]]

 [[16 18 13]
  [15 17 12]
  [15 15 13]
  ...
  [81 78 69]
  [80 77 72]
  [83 79 76]]

 [[17 19 16]
  [16 18 13]
  [17 18 13]
  ...
  [89 84 78]
  [84 79 75]
  [80 77 72]]

 ...

 [[58 59 54]
  [60 59 54]
  [58 59 53]
  ...
  [74 70 67]
  [68 69 64]
  [73 70 6

[[[ 32  34  29]
  [ 41  37  34]
  [ 41  40  35]
  ...
  [ 42  33  36]
  [ 48  30  28]
  [ 38  21  27]]

 [[ 27  28  23]
  [ 43  40  35]
  [ 34  33  28]
  ...
  [ 20  22  21]
  [ 52  41  39]
  [ 53  38  43]]

 [[ 39  40  34]
  [ 42  41  36]
  [ 38  37  32]
  ...
  [ 18  24  22]
  [ 24  26  21]
  [ 71  62  53]]

 ...

 [[ 58  57  53]
  [ 64  63  58]
  [ 63  60  55]
  ...
  [181 110  80]
  [174 105  74]
  [177 106  74]]

 [[ 61  60  55]
  [ 58  57  52]
  [ 61  60  55]
  ...
  [181 110  82]
  [179 110  79]
  [178 109  76]]

 [[ 60  59  55]
  [ 67  66  61]
  [ 62  61  56]
  ...
  [179 110  77]
  [180 111  78]
  [179 113  81]]] [1 0 0]
%%%%%: [1 0 0]


[[[ 68  61  45]
  [ 60  53  37]
  [ 64  57  41]
  ...
  [ 17  18  10]
  [ 19  18  13]
  [ 20  17  12]]

 [[ 73  66  50]
  [ 68  60  47]
  [ 66  58  45]
  ...
  [ 19  19  11]
  [ 24  21  16]
  [ 20  17  12]]

 [[ 70  61  46]
  [ 63  55  42]
  [ 67  59  46]
  ...
  [ 20  20  12]
  [ 23  20  15]
  [ 23  19  16]]

 ...

 [[170 102  67]
  [177 107 

%%%%%: [1 0 0]


[[[35 36 30]
  [36 35 30]
  [48 49 41]
  ...
  [16 15 11]
  [22 23 18]
  [11 12  6]]

 [[24 25 20]
  [33 32 27]
  [42 43 37]
  ...
  [23 24 19]
  [22 23 18]
  [23 22 17]]

 [[28 29 24]
  [42 41 36]
  [37 36 31]
  ...
  [24 24 22]
  [28 27 23]
  [25 22 17]]

 ...

 [[75 68 60]
  [76 69 59]
  [70 61 54]
  ...
  [20 20 18]
  [19 20 15]
  [19 20 15]]

 [[67 63 54]
  [71 62 53]
  [69 59 50]
  ...
  [18 20 17]
  [12 13  8]
  [15 16 11]]

 [[68 65 56]
  [73 64 55]
  [68 58 49]
  ...
  [13 13 11]
  [17 19 16]
  [18 20 15]]] [1 0 0]
%%%%%: [1 0 0]


[[[230  81  51]
  [225  77  49]
  [227  77  52]
  ...
  [217  83  46]
  [216  83  48]
  [217  84  49]]

 [[229  81  55]
  [226  78  52]
  [231  83  57]
  ...
  [219  87  48]
  [214  81  46]
  [213  80  45]]

 [[230  82  56]
  [228  80  54]
  [228  80  54]
  ...
  [211  78  43]
  [212  80  42]
  [217  85  47]]

 ...

 [[201  54  34]
  [199  52  32]
  [203  53  36]
  ...
  [189  54  34]
  [189  54  35]
  [187  53  26]]

 [[197  53  29

[[[ 6  6  4]
  [ 5  5  3]
  [ 9  4  8]
  ...
  [34 35 30]
  [40 39 35]
  [15 16 10]]

 [[ 4  4  2]
  [ 3  3  1]
  [ 3  3  1]
  ...
  [30 30 28]
  [20 21 16]
  [21 22 17]]

 [[ 6  6  4]
  [ 6  6  4]
  [ 4  4  2]
  ...
  [19 19 17]
  [18 20 15]
  [22 24 19]]

 ...

 [[27 28 23]
  [24 25 19]
  [26 26 18]
  ...
  [25 26 20]
  [24 25 20]
  [19 20 15]]

 [[14 19 13]
  [15 20 14]
  [20 23 14]
  ...
  [28 29 23]
  [23 25 20]
  [13 15 10]]

 [[12 14 11]
  [13 15 10]
  [19 20 12]
  ...
  [21 22 16]
  [31 32 27]
  [32 33 28]]] [1 0 0]
%%%%%: [1 0 0]


[[[37 38 32]
  [34 35 29]
  [31 32 27]
  ...
  [24 26 21]
  [13 15 10]
  [16 18 15]]

 [[29 28 24]
  [40 41 33]
  [27 28 23]
  ...
  [22 24 19]
  [16 18 13]
  [16 17 12]]

 [[35 34 29]
  [24 25 19]
  [21 21 19]
  ...
  [26 27 22]
  [23 24 19]
  [13 15 12]]

 ...

 [[32 32 30]
  [39 38 36]
  [43 44 39]
  ...
  [ 7  7  5]
  [ 6  8  7]
  [11 11  9]]

 [[47 46 42]
  [30 29 27]
  [46 46 44]
  ...
  [ 9  9  7]
  [ 3  5  2]
  [12 14 11]]

 [[35 32 25]
  [3

[[[76 69 61]
  [71 67 58]
  [72 72 62]
  ...
  [60 61 55]
  [54 55 49]
  [63 62 58]]

 [[72 68 59]
  [74 69 63]
  [70 70 62]
  ...
  [54 55 49]
  [51 52 46]
  [59 58 54]]

 [[68 68 60]
  [67 64 57]
  [67 67 59]
  ...
  [52 51 46]
  [57 58 52]
  [59 58 54]]

 ...

 [[65 64 60]
  [61 60 56]
  [61 60 56]
  ...
  [21 26 22]
  [19 24 20]
  [21 26 19]]

 [[68 64 61]
  [61 60 56]
  [71 67 64]
  ...
  [20 22 21]
  [15 20 16]
  [16 21 15]]

 [[62 62 54]
  [59 58 56]
  [62 61 59]
  ...
  [28 28 26]
  [15 17 16]
  [19 21 18]]] [1 0 0]
%%%%%: [1 0 0]


[[[38 39 34]
  [35 31 28]
  [31 30 26]
  ...
  [19 18 14]
  [21 21 19]
  [20 20 18]]

 [[30 31 23]
  [31 30 25]
  [42 43 38]
  ...
  [25 24 20]
  [27 27 25]
  [19 19 19]]

 [[36 36 26]
  [38 39 33]
  [41 42 36]
  ...
  [26 25 23]
  [19 18 16]
  [30 29 27]]

 ...

 [[78 71 63]
  [64 55 48]
  [73 64 57]
  ...
  [28 27 23]
  [17 17 15]
  [19 19 17]]

 [[71 64 56]
  [69 62 54]
  [67 58 53]
  ...
  [22 21 17]
  [27 28 23]
  [21 22 17]]

 [[70 61 54]
  [6

[[[152  85  56]
  [153  84  53]
  [152  83  50]
  ...
  [206  41  21]
  [208  43  24]
  [199  33  17]]

 [[155  88  59]
  [151  82  51]
  [151  80  48]
  ...
  [209  44  24]
  [209  42  23]
  [207  40  22]]

 [[160  89  61]
  [151  82  51]
  [151  80  48]
  ...
  [211  44  26]
  [209  42  23]
  [206  39  20]]

 ...

 [[201  79  42]
  [205  82  49]
  [203  78  46]
  ...
  [207  41  25]
  [207  41  25]
  [204  38  26]]

 [[195  72  38]
  [201  76  44]
  [204  79  49]
  ...
  [199  36  19]
  [203  37  21]
  [203  37  23]]

 [[200  79  32]
  [202  77  49]
  [201  76  48]
  ...
  [203  37  21]
  [201  35  19]
  [206  39  30]]] [1 0 0]
%%%%%: [1 0 0]


[[[ 43  42  47]
  [ 48  48  50]
  [ 33  45  43]
  ...
  [ 17  19  16]
  [ 18  20  17]
  [ 11  17  13]]

 [[ 32  36  47]
  [ 38  42  45]
  [ 34  46  44]
  ...
  [ 16  21  17]
  [ 13  18  14]
  [ 16  18  15]]

 [[ 38  41  50]
  [ 32  40  43]
  [ 33  42  41]
  ...
  [ 15  15  13]
  [ 15  17  14]
  [ 16  18  13]]

 ...

 [[126  72  60]
  [127  74 

%%%%%: [1 0 0]


[[[22 24 23]
  [23 23 21]
  [28 29 24]
  ...
  [48 60 56]
  [41 54 45]
  [40 52 48]]

 [[27 27 25]
  [24 23 19]
  [27 28 23]
  ...
  [47 57 48]
  [45 55 46]
  [46 57 49]]

 [[19 18 16]
  [21 22 17]
  [24 25 20]
  ...
  [55 57 52]
  [55 60 54]
  [43 48 42]]

 ...

 [[10 10  8]
  [ 7  8  3]
  [ 9 10  5]
  ...
  [31 36 29]
  [35 38 29]
  [28 33 26]]

 [[ 9  9  9]
  [10 10  8]
  [ 9  9  7]
  ...
  [37 40 31]
  [34 40 30]
  [30 36 26]]

 [[ 7  7  7]
  [ 7  8  3]
  [ 8  9  4]
  ...
  [33 38 31]
  [32 37 30]
  [27 32 25]]] [1 0 0]
%%%%%: [1 0 0]


[[[ 68  36  23]
  [ 69  35  26]
  [ 67  33  23]
  ...
  [ 38  35  30]
  [ 37  32  26]
  [ 35  30  24]]

 [[ 62  32  24]
  [ 65  32  25]
  [ 62  29  20]
  ...
  [ 37  34  27]
  [ 33  30  25]
  [ 35  32  27]]

 [[ 55  25  17]
  [ 61  28  21]
  [ 65  32  25]
  ...
  [ 36  33  28]
  [ 37  34  29]
  [ 36  33  28]]

 ...

 [[132  80  56]
  [138  87  66]
  [137  86  65]
  ...
  [ 16  17  12]
  [ 18  17  13]
  [ 23  19  16]]

 [[130  76  64

[[[227 107  90]
  [221 102  82]
  [222 101  82]
  ...
  [ 72  56  40]
  [ 77  54  40]
  [ 85  57  45]]

 [[230 110  93]
  [225 106  86]
  [226 107  85]
  ...
  [ 84  56  44]
  [ 80  57  43]
  [ 84  58  45]]

 [[223 113  88]
  [227 115  91]
  [227 113  87]
  ...
  [ 82  56  43]
  [ 82  55  44]
  [ 83  57  44]]

 ...

 [[215  74  57]
  [212  72  55]
  [212  72  59]
  ...
  [193  41  27]
  [190  37  21]
  [191  38  22]]

 [[211  72  51]
  [216  77  58]
  [213  74  55]
  ...
  [196  45  26]
  [190  39  22]
  [192  41  24]]

 [[207  70  51]
  [211  74  56]
  [209  71  58]
  ...
  [188  36  22]
  [196  40  27]
  [196  43  29]]] [1 0 0]
%%%%%: [1 0 0]


[[[184  15   8]
  [184  15   8]
  [183  14   9]
  ...
  [ 98   9   1]
  [ 94   9   2]
  [ 94  14   5]]

 [[183  16   7]
  [186  19  10]
  [187  20  11]
  ...
  [104  15   7]
  [ 97  10   3]
  [ 98  13   6]]

 [[185  18   9]
  [187  20  11]
  [186  20   8]
  ...
  [102  13   7]
  [103  14   8]
  [101  12   6]]

 ...

 [[231 123  97]
  [235 129 

[[[17 19 16]
  [22 23 18]
  [29 31 26]
  ...
  [62 58 55]
  [62 63 58]
  [63 55 53]]

 [[28 30 25]
  [27 30 23]
  [26 29 22]
  ...
  [63 62 57]
  [53 52 48]
  [56 57 52]]

 [[27 28 20]
  [29 30 25]
  [25 26 20]
  ...
  [53 52 48]
  [48 47 43]
  [44 43 39]]

 ...

 [[ 7  7  5]
  [12 12 10]
  [10  9  5]
  ...
  [39 39 31]
  [25 27 16]
  [35 35 27]]

 [[ 8  7  5]
  [ 7  6  2]
  [10  9  5]
  ...
  [63 65 54]
  [43 45 34]
  [39 36 27]]

 [[ 3  2  0]
  [ 9  8  4]
  [ 7  6  4]
  ...
  [41 41 31]
  [39 41 30]
  [37 37 27]]] [1 0 0]
%%%%%: [1 0 0]


[[[14 11  6]
  [11 10  5]
  [ 9  8  6]
  ...
  [74 72 59]
  [70 67 50]
  [77 71 55]]

 [[16 13  8]
  [11 10  5]
  [12 11  7]
  ...
  [74 70 58]
  [66 63 46]
  [71 68 49]]

 [[14 10  7]
  [11 10  6]
  [11 12  7]
  ...
  [76 72 60]
  [70 66 54]
  [74 69 50]]

 ...

 [[49 49 39]
  [50 53 42]
  [51 51 41]
  ...
  [53 59 49]
  [54 62 51]
  [61 61 49]]

 [[51 51 39]
  [47 49 38]
  [52 54 43]
  ...
  [55 61 49]
  [46 56 45]
  [66 63 54]]

 [[51 53 39]
  [4

[[[211 196 177]
  [210 195 174]
  [209 192 172]
  ...
  [200 185 164]
  [203 186 168]
  [203 184 169]]

 [[210 197 178]
  [213 198 177]
  [212 197 176]
  ...
  [206 190 167]
  [207 192 171]
  [200 183 163]]

 [[208 195 176]
  [209 194 173]
  [209 194 173]
  ...
  [204 188 165]
  [203 187 164]
  [203 187 164]]

 ...

 [[143 127 101]
  [147 131 105]
  [147 131 108]
  ...
  [143 123  96]
  [141 120 103]
  [137 119  97]]

 [[143 127 102]
  [145 130 101]
  [147 131 106]
  ...
  [141 119  95]
  [134 116  94]
  [136 119  93]]

 [[144 124  97]
  [155 135 108]
  [144 128  94]
  ...
  [141 118  87]
  [142 127  88]
  [132 118  69]]] [1 0 0]
%%%%%: [1 0 0]


[[[39 28 26]
  [50 40 30]
  [49 39 29]
  ...
  [12 12 10]
  [11 13  8]
  [12 14 11]]

 [[40 29 25]
  [45 37 26]
  [42 33 24]
  ...
  [12 12 10]
  [12 14  9]
  [10 12  9]]

 [[44 30 27]
  [49 36 27]
  [49 39 29]
  ...
  [13 14  9]
  [10 12  7]
  [11 12  7]]

 ...

 [[ 3  2  0]
  [ 9  8  4]
  [ 8  7  3]
  ...
  [30 32 27]
  [34 35 30]
  [31 27 2

[[[184 177 151]
  [193 181 155]
  [202 188 162]
  ...
  [233 218 197]
  [235 222 203]
  [234 223 203]]

 [[199 183 157]
  [197 181 155]
  [199 185 159]
  ...
  [235 222 203]
  [235 222 203]
  [232 221 201]]

 [[200 183 165]
  [199 183 160]
  [197 181 158]
  ...
  [235 220 201]
  [237 224 205]
  [232 221 199]]

 ...

 [[184 161 143]
  [191 169 145]
  [188 168 144]
  ...
  [238 223 200]
  [238 223 200]
  [233 221 197]]

 [[196 173 155]
  [194 174 150]
  [189 169 144]
  ...
  [237 222 199]
  [234 222 200]
  [235 224 202]]

 [[187 166 147]
  [192 173 143]
  [192 172 148]
  ...
  [238 223 200]
  [234 222 200]
  [238 227 207]]] [1 0 0]
%%%%%: [1 0 0]


[[[220  58  37]
  [218  55  36]
  [217  57  35]
  ...
  [208  41  22]
  [208  43  24]
  [210  45  26]]

 [[218  56  35]
  [219  56  37]
  [220  59  39]
  ...
  [210  43  24]
  [216  49  31]
  [214  47  29]]

 [[222  60  39]
  [218  57  37]
  [219  56  37]
  ...
  [211  44  25]
  [209  42  24]
  [210  43  25]]

 ...

 [[158  36  23]
  [159  37 

[[[32 29 24]
  [32 29 24]
  [35 29 29]
  ...
  [55 56 48]
  [50 43 37]
  [52 47 41]]

 [[29 28 24]
  [29 25 22]
  [35 30 27]
  ...
  [41 44 35]
  [47 43 34]
  [52 45 37]]

 [[27 28 22]
  [28 27 22]
  [31 26 22]
  ...
  [40 43 32]
  [51 48 39]
  [49 46 37]]

 ...

 [[75 75 67]
  [71 71 63]
  [72 71 66]
  ...
  [65 62 55]
  [62 59 54]
  [61 60 55]]

 [[71 71 59]
  [72 72 60]
  [73 73 63]
  ...
  [67 64 57]
  [70 67 60]
  [61 61 53]]

 [[74 75 61]
  [72 73 59]
  [73 73 61]
  ...
  [61 61 51]
  [62 59 50]
  [62 61 56]]] [1 0 0]
%%%%%: [1 0 0]


[[[19 21 18]
  [15 17 14]
  [15 17 14]
  ...
  [72 71 66]
  [79 78 74]
  [65 62 57]]

 [[15 20 16]
  [15 20 14]
  [17 22 18]
  ...
  [79 80 74]
  [82 81 77]
  [83 82 77]]

 [[18 20 15]
  [17 19 14]
  [16 18 15]
  ...
  [82 83 77]
  [79 80 75]
  [78 78 76]]

 ...

 [[66 66 58]
  [64 64 56]
  [65 66 60]
  ...
  [71 72 66]
  [74 75 70]
  [72 73 68]]

 [[66 68 57]
  [70 73 62]
  [64 64 56]
  ...
  [71 74 65]
  [69 70 64]
  [73 74 68]]

 [[60 66 52]
  [6

[[[ 23  25  22]
  [ 20  21  15]
  [ 23  22  17]
  ...
  [219 203 180]
  [224 209 186]
  [221 209 185]]

 [[ 26  26  24]
  [ 20  21  15]
  [ 23  24  18]
  ...
  [219 205 179]
  [220 208 182]
  [219 207 181]]

 [[ 15  15  13]
  [ 20  21  15]
  [ 23  24  18]
  ...
  [217 205 181]
  [219 207 181]
  [218 206 180]]

 ...

 [[ 51  51  43]
  [ 45  44  39]
  [ 42  42  34]
  ...
  [225 213 187]
  [225 213 187]
  [226 214 188]]

 [[ 48  47  42]
  [ 44  43  38]
  [ 46  43  38]
  ...
  [225 213 187]
  [223 211 187]
  [224 214 189]]

 [[ 46  45  40]
  [ 44  44  34]
  [ 38  39  31]
  ...
  [224 212 188]
  [223 211 187]
  [223 212 192]]] [1 0 0]
%%%%%: [1 0 0]


[[[ 48  46  33]
  [ 43  40  31]
  [ 50  50  42]
  ...
  [ 12  14  13]
  [ 14  16  13]
  [ 12  14  11]]

 [[ 49  47  34]
  [ 48  48  36]
  [ 49  49  39]
  ...
  [ 10  12  11]
  [ 11  13  10]
  [ 10  12   9]]

 [[ 44  44  32]
  [ 46  46  38]
  [ 47  49  36]
  ...
  [ 11  13  12]
  [  9  11  10]
  [  9  11   8]]

 ...

 [[158  93  53]
  [159  93 

%%%%%: [1 0 0]


[[[30 31 25]
  [19 20 15]
  [27 30 21]
  ...
  [29 31 26]
  [12 17 11]
  [24 25 20]]

 [[19 20 15]
  [35 36 31]
  [35 36 28]
  ...
  [22 23 18]
  [22 23 18]
  [18 19 14]]

 [[28 28 26]
  [28 29 24]
  [36 37 31]
  ...
  [22 23 18]
  [18 19 14]
  [17 18 13]]

 ...

 [[30 30 32]
  [34 34 34]
  [31 33 32]
  ...
  [ 9  9  9]
  [ 6  6  6]
  [ 8 10  7]]

 [[31 31 31]
  [30 30 30]
  [29 31 30]
  ...
  [ 9  9  7]
  [ 7  7  5]
  [ 7  8 10]]

 [[35 35 33]
  [29 29 27]
  [32 34 33]
  ...
  [ 8  8  6]
  [ 6  7  2]
  [ 6  8  5]]] [1 0 0]
%%%%%: [1 0 0]


[[[14 15 10]
  [14 15 10]
  [14 15 10]
  ...
  [75 69 69]
  [72 64 61]
  [70 59 57]]

 [[16 18 13]
  [10 12  7]
  [10 11  6]
  ...
  [72 68 65]
  [66 61 57]
  [70 67 60]]

 [[14 15 10]
  [11 13  8]
  [13 14  9]
  ...
  [67 62 59]
  [70 65 61]
  [69 64 61]]

 ...

 [[64 63 58]
  [58 57 53]
  [63 59 56]
  ...
  [55 54 49]
  [58 54 51]
  [58 55 50]]

 [[49 51 40]
  [63 64 56]
  [57 54 49]
  ...
  [56 57 51]
  [52 51 47]
  [56 55 50]]



[[[192  65  56]
  [193  69  57]
  [194  71  56]
  ...
  [217  65  52]
  [218  67  50]
  [219  68  51]]

 [[189  67  52]
  [188  65  50]
  [194  71  56]
  ...
  [220  69  50]
  [221  70  53]
  [220  69  52]]

 [[184  62  49]
  [184  62  49]
  [186  64  49]
  ...
  [215  64  47]
  [223  71  50]
  [215  64  43]]

 ...

 [[187  27  13]
  [192  32  20]
  [185  25  13]
  ...
  [201  58  44]
  [201  59  47]
  [206  61  56]]

 [[188  25  16]
  [186  26  14]
  [187  27  15]
  ...
  [200  57  43]
  [206  63  49]
  [205  63  49]]

 [[185  24  14]
  [185  25  13]
  [184  24  12]
  ...
  [201  58  44]
  [202  61  44]
  [202  62  35]]] [1 0 0]
%%%%%: [1 0 0]


[[[19 20 14]
  [17 20 13]
  [27 28 23]
  ...
  [82 79 74]
  [88 84 81]
  [80 81 75]]

 [[20 20 18]
  [21 22 17]
  [20 19 14]
  ...
  [81 81 73]
  [79 78 73]
  [80 81 75]]

 [[20 21 15]
  [21 22 16]
  [23 24 18]
  ...
  [82 79 70]
  [78 78 68]
  [79 81 70]]

 ...

 [[68 71 60]
  [70 73 62]
  [72 74 63]
  ...
  [63 60 53]
  [64 64 56]
  [57 54 4

[[[182 194 206]
  [183 196 205]
  [183 196 205]
  ...
  [175 187 201]
  [181 195 208]
  [170 192 203]]

 [[181 195 206]
  [183 196 205]
  [182 196 205]
  ...
  [177 191 204]
  [178 192 205]
  [173 191 203]]

 [[180 192 204]
  [185 198 207]
  [184 198 209]
  ...
  [180 193 209]
  [182 195 211]
  [176 188 204]]

 ...

 [[152 162 171]
  [157 167 176]
  [157 166 173]
  ...
  [185 199 210]
  [183 196 205]
  [181 196 203]]

 [[159 163 175]
  [158 167 174]
  [159 168 175]
  ...
  [183 197 206]
  [185 199 208]
  [186 201 208]]

 [[153 166 175]
  [159 169 178]
  [159 166 174]
  ...
  [182 196 205]
  [183 197 206]
  [181 196 203]]] [0 1 0]
%%%%%: [0 1 0]


[[[107 114 120]
  [110 115 119]
  [103 107 110]
  ...
  [ 31  23  10]
  [ 33  27  13]
  [ 26  23   8]]

 [[109 117 120]
  [108 113 117]
  [108 116 119]
  ...
  [ 33  27  13]
  [ 33  27  13]
  [ 30  24  10]]

 [[105 115 117]
  [108 118 120]
  [111 121 123]
  ...
  [ 33  27  13]
  [ 34  28  14]
  [ 32  26  12]]

 ...

 [[155 171 187]
  [162 179 

[[[ 49  36  20]
  [ 44  31  15]
  [ 45  32  16]
  ...
  [201 203 181]
  [198 200 179]
  [198 200 179]]

 [[ 47  34  18]
  [ 43  30  14]
  [ 49  36  20]
  ...
  [199 201 179]
  [199 201 180]
  [199 201 180]]

 [[ 51  38  22]
  [ 50  37  21]
  [ 49  36  20]
  ...
  [199 201 179]
  [201 203 182]
  [201 203 182]]

 ...

 [[175 156 124]
  [173 158 125]
  [173 158 127]
  ...
  [127 122 102]
  [125 120 100]
  [129 124 104]]

 [[177 158 126]
  [173 157 124]
  [173 158 127]
  ...
  [127 122 102]
  [127 122 102]
  [125 122 103]]

 [[174 157 129]
  [168 154 125]
  [171 156 125]
  ...
  [126 121 102]
  [127 122 102]
  [126 123 104]]] [0 1 0]
%%%%%: [0 1 0]


[[[ 73  52  23]
  [ 67  46  17]
  [ 79  58  27]
  ...
  [195  73  50]
  [190  69  48]
  [190  68  47]]

 [[ 72  51  22]
  [ 67  46  17]
  [ 72  51  20]
  ...
  [189  67  44]
  [191  70  49]
  [190  68  47]]

 [[ 74  53  24]
  [ 72  51  22]
  [ 78  57  26]
  ...
  [201  79  56]
  [191  70  49]
  [192  70  49]]

 ...

 [[172  41  13]
  [177  46 

[[[178 190 204]
  [178 190 202]
  [174 186 200]
  ...
  [160 176 191]
  [160 176 191]
  [161 177 192]]

 [[173 185 199]
  [173 185 197]
  [180 192 204]
  ...
  [158 174 189]
  [162 178 193]
  [159 175 190]]

 [[169 181 195]
  [177 189 203]
  [176 188 202]
  ...
  [160 171 189]
  [162 178 193]
  [153 169 184]]

 ...

 [[137 147 157]
  [141 149 160]
  [147 155 166]
  ...
  [168 178 190]
  [172 182 194]
  [168 180 192]]

 [[147 156 165]
  [144 154 163]
  [144 154 163]
  ...
  [164 174 186]
  [167 179 191]
  [170 182 196]]

 [[130 139 148]
  [142 152 161]
  [144 154 163]
  ...
  [166 176 188]
  [162 174 186]
  [165 176 194]]] [0 1 0]
%%%%%: [0 1 0]


[[[ 87 101 114]
  [ 83  99 112]
  [ 77  90 106]
  ...
  [135 163 177]
  [138 164 179]
  [136 162 175]]

 [[ 83  97 110]
  [ 81  97 110]
  [ 80  98 110]
  ...
  [139 165 180]
  [137 163 178]
  [140 166 179]]

 [[ 84 100 113]
  [ 78  96 108]
  [ 82  98 111]
  ...
  [136 164 178]
  [134 160 175]
  [136 162 177]]

 ...

 [[139 166 183]
  [139 165 

[[[222 214 178]
  [223 215 179]
  [224 216 180]
  ...
  [222 220 197]
  [222 220 197]
  [223 221 198]]

 [[222 213 180]
  [223 214 181]
  [223 214 181]
  ...
  [224 222 199]
  [223 221 200]
  [224 222 201]]

 [[225 216 183]
  [223 214 181]
  [223 214 181]
  ...
  [224 222 201]
  [224 222 201]
  [223 221 200]]

 ...

 [[ 14  15  10]
  [ 15  16  11]
  [ 16  17  12]
  ...
  [122 116  92]
  [ 96  90  74]
  [ 45  35  33]]

 [[ 16  17  12]
  [ 16  17  12]
  [ 15  16  11]
  ...
  [109 102  83]
  [ 45  41  29]
  [ 27  19  16]]

 [[ 17  17  15]
  [ 12  12  10]
  [ 16  16  14]
  ...
  [ 54  47  37]
  [ 25  22  17]
  [ 15   9   9]]] [0 1 0]
%%%%%: [0 1 0]


[[[181 189 202]
  [181 189 202]
  [181 189 202]
  ...
  [174 186 200]
  [176 186 198]
  [177 187 199]]

 [[180 188 201]
  [181 189 202]
  [182 190 203]
  ...
  [174 186 200]
  [177 187 199]
  [177 186 201]]

 [[180 188 201]
  [180 188 201]
  [183 191 204]
  ...
  [174 186 200]
  [178 187 202]
  [178 187 202]]

 ...

 [[162 166 178]
  [165 169 

[[[241 229 181]
  [241 229 181]
  [241 229 181]
  ...
  [241 233 197]
  [240 234 200]
  [244 235 202]]

 [[240 228 180]
  [240 228 180]
  [241 229 181]
  ...
  [241 233 197]
  [241 235 201]
  [245 236 203]]

 [[241 229 181]
  [242 230 182]
  [241 229 181]
  ...
  [242 234 198]
  [241 235 201]
  [243 234 201]]

 ...

 [[217 199 149]
  [162 147 106]
  [127 116  88]
  ...
  [207 198 159]
  [206 197 158]
  [210 201 162]]

 [[217 195 145]
  [211 191 140]
  [215 194 147]
  ...
  [202 193 154]
  [208 199 160]
  [208 200 163]]

 [[211 190 143]
  [208 190 144]
  [210 191 149]
  ...
  [205 195 159]
  [207 198 159]
  [207 199 162]]] [0 1 0]
%%%%%: [0 1 0]


[[[ 50  32  10]
  [ 49  31   9]
  [ 45  27   5]
  ...
  [198  89  68]
  [205  96  76]
  [209  98  79]]

 [[ 47  29   7]
  [ 49  31   9]
  [ 49  31   9]
  ...
  [202  93  72]
  [199  90  70]
  [203  92  73]]

 [[ 50  32  10]
  [ 49  31   9]
  [ 51  33  11]
  ...
  [198  89  68]
  [205  96  76]
  [203  92  73]]

 ...

 [[ 60  34   7]
  [ 63  40 

[[[ 58  45  28]
  [ 60  47  30]
  [ 57  46  28]
  ...
  [195 198 179]
  [195 198 179]
  [196 199 180]]

 [[ 58  45  28]
  [ 58  45  28]
  [ 58  47  29]
  ...
  [194 197 178]
  [196 199 180]
  [196 199 180]]

 [[ 58  45  28]
  [ 58  45  28]
  [ 59  48  30]
  ...
  [195 198 179]
  [196 199 180]
  [195 198 179]]

 ...

 [[187 173 146]
  [187 173 146]
  [184 173 145]
  ...
  [128 126 103]
  [126 124 101]
  [125 123 100]]

 [[188 174 147]
  [187 173 146]
  [185 174 146]
  ...
  [125 123 100]
  [127 125 102]
  [127 125 104]]

 [[184 172 146]
  [184 172 146]
  [184 172 146]
  ...
  [126 124 103]
  [126 124 101]
  [125 123 102]]] [0 1 0]
%%%%%: [0 1 0]


[[[101 115 126]
  [103 117 128]
  [100 114 127]
  ...
  [157 183 198]
  [175 198 216]
  [172 195 213]]

 [[ 97 115 127]
  [100 117 127]
  [101 115 126]
  ...
  [167 193 210]
  [170 193 211]
  [170 193 211]]

 [[ 98 116 126]
  [100 118 128]
  [103 117 128]
  ...
  [168 191 209]
  [171 194 212]
  [170 193 211]]

 ...

 [[156 182 199]
  [155 181 

%%%%%: [0 1 0]


[[[102 100  85]
  [107 106  88]
  [114 111  92]
  ...
  [ 41  37  28]
  [ 44  39  33]
  [ 38  33  27]]

 [[107 107  95]
  [109 107  92]
  [111 108  99]
  ...
  [ 39  35  26]
  [ 35  31  22]
  [ 41  38  29]]

 [[107 105  92]
  [106 104  91]
  [111 109  96]
  ...
  [ 42  38  29]
  [ 36  31  25]
  [ 36  31  25]]

 ...

 [[163 164 158]
  [161 162 154]
  [163 166 159]
  ...
  [175 176 170]
  [173 176 169]
  [175 178 171]]

 [[164 167 158]
  [161 164 155]
  [157 160 151]
  ...
  [177 178 170]
  [175 178 169]
  [175 178 169]]

 [[163 164 156]
  [162 165 156]
  [163 166 157]
  ...
  [176 177 169]
  [175 178 169]
  [174 177 168]]] [0 1 0]
%%%%%: [0 1 0]


[[[110 106  95]
  [113 109  98]
  [115 106  99]
  ...
  [ 42  30  14]
  [ 39  30  13]
  [ 51  42  27]]

 [[117 113 101]
  [114 110  98]
  [117 111  99]
  ...
  [ 40  29  11]
  [ 36  25   7]
  [ 52  40  24]]

 [[114 110  99]
  [115 111 100]
  [117 110 100]
  ...
  [ 38  27   9]
  [ 44  33  15]
  [ 50  39  21]]

 ...

 [[172 175

[[[110 107  98]
  [115 112 103]
  [111 109  96]
  ...
  [145 148 141]
  [145 148 141]
  [145 148 141]]

 [[106 104  92]
  [109 107  95]
  [106 104  92]
  ...
  [152 155 146]
  [148 151 142]
  [150 153 146]]

 [[104 102  90]
  [103 101  89]
  [105 102  93]
  ...
  [150 153 144]
  [151 154 145]
  [150 153 144]]

 ...

 [[147 153 143]
  [148 154 144]
  [148 151 142]
  ...
  [166 171 165]
  [162 164 159]
  [163 168 164]]

 [[147 153 141]
  [146 152 140]
  [148 151 142]
  ...
  [165 170 163]
  [161 166 160]
  [162 167 163]]

 [[148 153 146]
  [149 155 143]
  [154 157 148]
  ...
  [161 167 157]
  [162 167 160]
  [164 169 163]]] [0 1 0]
%%%%%: [0 1 0]


[[[176 187 207]
  [176 187 207]
  [172 183 201]
  ...
  [181 196 217]
  [183 196 215]
  [183 195 217]]

 [[179 190 210]
  [176 187 207]
  [178 189 207]
  ...
  [181 196 217]
  [183 198 217]
  [182 197 218]]

 [[179 190 210]
  [179 190 210]
  [179 190 208]
  ...
  [183 195 217]
  [187 200 219]
  [184 196 218]]

 ...

 [[162 169 188]
  [162 169 

[[[113  79  31]
  [114  80  32]
  [107  73  27]
  ...
  [137 124 107]
  [132 120 104]
  [147 134 118]]

 [[113  79  31]
  [111  77  29]
  [115  81  33]
  ...
  [139 126 109]
  [142 130 114]
  [143 130 114]]

 [[118  84  36]
  [112  78  30]
  [113  79  31]
  ...
  [145 132 116]
  [145 133 117]
  [135 122 106]]

 ...

 [[ 91  59  18]
  [ 91  59  18]
  [101  70  24]
  ...
  [ 48  31  11]
  [ 49  32  14]
  [ 43  26  10]]

 [[ 91  59  18]
  [101  70  26]
  [ 95  62  19]
  ...
  [ 45  28   8]
  [ 46  30  14]
  [ 36  20   5]]

 [[ 84  54  16]
  [ 88  59  19]
  [ 90  58  19]
  ...
  [ 43  26   8]
  [ 41  25   9]
  [ 43  29  16]]] [0 1 0]
%%%%%: [0 1 0]


[[[ 83 101 105]
  [ 90 103 112]
  [ 82  95 104]
  ...
  [153 172 187]
  [146 169 183]
  [139 163 175]]

 [[ 88 101 110]
  [ 84  98 107]
  [ 89 102 111]
  ...
  [149 171 185]
  [149 171 185]
  [149 171 185]]

 [[ 84  98 107]
  [ 87 101 112]
  [ 87 100 109]
  ...
  [150 172 186]
  [149 171 185]
  [150 172 186]]

 ...

 [[143 165 179]
  [143 165 

[[[ 57  40  22]
  [ 56  39  21]
  [ 47  30  10]
  ...
  [220 220 194]
  [219 219 195]
  [219 219 195]]

 [[ 56  39  21]
  [ 56  39  21]
  [ 64  47  27]
  ...
  [219 219 195]
  [218 217 196]
  [219 218 197]]

 [[ 57  40  22]
  [ 57  40  22]
  [ 58  41  21]
  ...
  [220 219 198]
  [220 219 199]
  [219 218 198]]

 ...

 [[ 43  40  35]
  [114 111  92]
  [148 143 124]
  ...
  [  3   3   1]
  [  3   5   2]
  [  3   5   2]]

 [[ 20  19  17]
  [ 31  27  24]
  [ 23  20  13]
  ...
  [  3   3   1]
  [  3   5   2]
  [  3   5   2]]

 [[ 21  20  18]
  [ 18  17  15]
  [ 29  25  24]
  ...
  [  5   5   3]
  [  2   4   1]
  [  2   4   1]]] [0 1 0]
%%%%%: [0 1 0]


[[[120  19  11]
  [119  18  10]
  [116  15   7]
  ...
  [156  35  18]
  [152  31  14]
  [153  32  15]]

 [[115  17   8]
  [115  17   8]
  [118  17   9]
  ...
  [151  30  13]
  [150  29  12]
  [151  30  13]]

 [[118  17   9]
  [118  17   9]
  [121  20  12]
  ...
  [151  30  13]
  [151  30  13]
  [153  32  15]]

 ...

 [[174  96  86]
  [172  94 

[[[ 57  44  25]
  [ 56  43  24]
  [ 57  44  25]
  ...
  [191 194 173]
  [191 194 175]
  [194 197 178]]

 [[ 57  44  25]
  [ 57  44  25]
  [ 57  44  25]
  ...
  [190 193 172]
  [192 195 176]
  [189 192 173]]

 [[ 56  43  24]
  [ 57  44  25]
  [ 59  46  27]
  ...
  [191 194 173]
  [191 194 177]
  [191 194 177]]

 ...

 [[191 177 148]
  [189 175 146]
  [187 173 146]
  ...
  [120 118  97]
  [120 118  97]
  [120 118  97]]

 [[189 175 146]
  [189 175 146]
  [187 173 146]
  ...
  [120 118  97]
  [121 119  98]
  [120 117  98]]

 [[189 177 151]
  [187 175 149]
  [188 174 148]
  ...
  [119 116  97]
  [119 117  96]
  [121 118  99]]] [0 1 0]
%%%%%: [0 1 0]


[[[ 80  72  61]
  [ 78  70  59]
  [ 79  71  60]
  ...
  [176 188 200]
  [178 188 198]
  [178 188 200]]

 [[ 79  71  60]
  [ 80  72  61]
  [ 80  72  61]
  ...
  [174 186 198]
  [176 186 196]
  [175 185 197]]

 [[ 80  72  61]
  [ 77  69  58]
  [ 80  72  59]
  ...
  [175 187 199]
  [178 188 198]
  [178 188 200]]

 ...

 [[181 194 203]
  [181 194 

[[[118  17   7]
  [115  14   2]
  [113  12   0]
  ...
  [163  31  10]
  [165  35  13]
  [163  33  11]]

 [[115  17   6]
  [111  13   2]
  [114  16   3]
  ...
  [165  35  13]
  [166  36  12]
  [167  37  15]]

 [[114  16   5]
  [113  15   4]
  [116  18   7]
  ...
  [164  34  12]
  [164  34  12]
  [166  34  11]]

 ...

 [[171  66  37]
  [174  66  37]
  [178  68  41]
  ...
  [188  70  44]
  [187  69  41]
  [188  70  42]]

 [[170  65  35]
  [173  65  36]
  [175  67  39]
  ...
  [184  66  40]
  [185  70  43]
  [185  70  41]]

 [[171  68  33]
  [171  66  37]
  [170  65  35]
  ...
  [184  66  40]
  [184  69  40]
  [189  71  43]]] [0 1 0]
%%%%%: [0 1 0]


[[[167  37  13]
  [179  49  27]
  [175  38  20]
  ...
  [ 63  34  20]
  [ 72  46  19]
  [ 80  46  21]]

 [[175  45  21]
  [173  43  19]
  [173  41  20]
  ...
  [ 64  39  19]
  [ 64  38  15]
  [ 68  42  15]]

 [[173  43  21]
  [171  41  17]
  [181  49  26]
  ...
  [ 73  53  46]
  [ 65  37  16]
  [ 71  49  25]]

 ...

 [[207  47  25]
  [208  50 

[[[146 158 170]
  [164 177 186]
  [160 174 183]
  ...
  [172 184 196]
  [174 186 200]
  [173 185 199]]

 [[171 181 191]
  [158 171 180]
  [164 177 186]
  ...
  [172 184 196]
  [175 187 201]
  [172 184 198]]

 [[171 184 193]
  [162 175 184]
  [162 175 184]
  ...
  [172 184 196]
  [175 184 199]
  [177 186 201]]

 ...

 [[139 143 152]
  [131 138 146]
  [140 147 155]
  ...
  [181 191 201]
  [183 196 205]
  [185 195 204]]

 [[152 159 165]
  [138 145 151]
  [142 151 158]
  ...
  [180 190 200]
  [183 196 205]
  [179 192 200]]

 [[140 151 153]
  [147 152 158]
  [141 152 158]
  ...
  [187 197 207]
  [179 193 202]
  [179 194 201]]] [0 1 0]
%%%%%: [0 1 0]


[[[ 47  36  18]
  [ 50  37  20]
  [ 55  39  23]
  ...
  [203 205 181]
  [207 209 188]
  [206 208 187]]

 [[ 47  36  18]
  [ 49  36  19]
  [ 54  38  22]
  ...
  [198 200 176]
  [204 206 185]
  [207 209 188]]

 [[ 47  36  18]
  [ 49  36  19]
  [ 54  38  22]
  ...
  [206 208 184]
  [204 206 185]
  [205 207 186]]

 ...

 [[187 167 134]
  [187 167 

[[[107  17   6]
  [110  18   7]
  [105  13   2]
  ...
  [160  27   8]
  [164  29  10]
  [164  29  10]]

 [[109  17   6]
  [108  16   5]
  [108  16   3]
  ...
  [164  33  13]
  [163  32  12]
  [163  32  12]]

 [[109  17   6]
  [108  16   5]
  [106  17   3]
  ...
  [161  31   9]
  [163  33  11]
  [161  31   9]]

 ...

 [[174  66  37]
  [173  68  36]
  [181  73  44]
  ...
  [190  64  39]
  [192  68  42]
  [191  67  41]]

 [[175  67  38]
  [171  66  34]
  [179  74  42]
  ...
  [189  65  39]
  [199  75  49]
  [191  65  40]]

 [[175  68  36]
  [172  67  35]
  [174  71  36]
  ...
  [191  67  41]
  [192  67  39]
  [193  68  40]]] [0 1 0]
%%%%%: [0 1 0]


[[[ 98 106 109]
  [ 95 105 106]
  [108 116 119]
  ...
  [ 29  20  11]
  [ 28  20   7]
  [ 35  27  14]]

 [[ 94 104 106]
  [ 93 103 104]
  [ 97 102 106]
  ...
  [ 29  23  11]
  [ 36  30  16]
  [ 29  23   9]]

 [[ 92 104 104]
  [ 92 104 104]
  [ 91  99 102]
  ...
  [ 33  27  15]
  [ 31  25  11]
  [ 31  25  11]]

 ...

 [[162 180 192]
  [163 183 

[[[ 91  91  79]
  [103 104  90]
  [107 104  89]
  ...
  [149 149 139]
  [147 149 138]
  [147 150 139]]

 [[104 102  89]
  [104 102  89]
  [111 109  96]
  ...
  [148 150 137]
  [151 153 140]
  [148 150 139]]

 [[107 103  91]
  [106 104  91]
  [108 107  89]
  ...
  [152 154 141]
  [148 152 138]
  [147 150 139]]

 ...

 [[156 157 151]
  [154 157 148]
  [158 159 151]
  ...
  [172 172 162]
  [174 174 166]
  [170 170 160]]

 [[154 157 150]
  [156 157 149]
  [154 157 146]
  ...
  [171 171 163]
  [171 172 164]
  [170 170 162]]

 [[160 162 157]
  [154 155 147]
  [154 157 148]
  ...
  [171 172 164]
  [169 170 162]
  [170 170 162]]] [0 1 0]
%%%%%: [0 1 0]


[[[106  12   4]
  [107  19   7]
  [104  11   3]
  ...
  [159  26   7]
  [158  22   6]
  [159  27   6]]

 [[110  18   7]
  [103  15   3]
  [111  21  12]
  ...
  [160  27   8]
  [162  26  10]
  [158  25   6]]

 [[107  15   4]
  [106  16   5]
  [106  14   3]
  ...
  [161  28   9]
  [159  26   9]
  [161  25   9]]

 ...

 [[174  67  35]
  [173  66 

[[[196 192 163]
  [197 192 163]
  [198 193 164]
  ...
  [197 195 170]
  [199 197 174]
  [202 200 177]]

 [[196 192 165]
  [197 191 165]
  [198 192 166]
  ...
  [198 196 171]
  [201 199 176]
  [200 198 175]]

 [[197 193 168]
  [199 193 169]
  [198 192 168]
  ...
  [197 195 170]
  [199 197 174]
  [201 201 177]]

 ...

 [[192 178 143]
  [191 177 142]
  [193 179 144]
  ...
  [  9   9   7]
  [  9   9   7]
  [  8   8   6]]

 [[193 179 144]
  [193 179 144]
  [193 179 144]
  ...
  [ 11  11   9]
  [  9   9   7]
  [  8   8   6]]

 [[190 177 145]
  [189 176 144]
  [190 176 141]
  ...
  [ 11  11   9]
  [  9   9   7]
  [  8   8   6]]] [0 1 0]
%%%%%: [0 1 0]


[[[ 35  26  11]
  [ 50  37  18]
  [ 53  38  17]
  ...
  [162  53  33]
  [163  56  38]
  [172  62  45]]

 [[ 39  30  15]
  [ 49  36  17]
  [ 54  39  18]
  ...
  [162  53  33]
  [161  54  36]
  [164  54  37]]

 [[ 42  33  18]
  [ 52  39  20]
  [ 55  40  19]
  ...
  [166  57  37]
  [162  55  37]
  [166  56  39]]

 ...

 [[ 29  16   0]
  [ 31  18 

[[[177 184 202]
  [173 185 201]
  [173 185 199]
  ...
  [177 192 211]
  [172 184 200]
  [175 186 204]]

 [[178 185 203]
  [175 187 203]
  [172 184 198]
  ...
  [174 189 208]
  [175 187 203]
  [175 186 204]]

 [[176 183 201]
  [176 188 204]
  [174 186 200]
  ...
  [172 187 206]
  [175 187 203]
  [175 186 204]]

 ...

 [[148 155 171]
  [154 161 177]
  [148 155 171]
  ...
  [ 84  90 102]
  [ 85  91 103]
  [ 80  86  98]]

 [[146 153 169]
  [145 152 168]
  [144 151 167]
  ...
  [ 81  87  99]
  [ 83  89 101]
  [ 88  95 105]]

 [[142 148 162]
  [147 153 167]
  [145 151 167]
  ...
  [ 86  90 102]
  [ 81  87  99]
  [ 77  86  93]]] [0 1 0]
%%%%%: [0 1 0]


[[[116 133 141]
  [119 130 134]
  [116 122 122]
  ...
  [ 31  24   8]
  [ 32  23   8]
  [ 32  23   8]]

 [[119 129 138]
  [112 122 132]
  [ 64  72  75]
  ...
  [ 31  24   8]
  [ 34  27  11]
  [ 35  26   9]]

 [[112 127 134]
  [113 124 128]
  [ 42  50  53]
  ...
  [ 30  23   7]
  [ 32  25   9]
  [ 32  25   9]]

 ...

 [[167 144 150]
  [123 144 

In [26]:
print(label)

Tensor("Cast_1:0", shape=(), dtype=int32)


In [4]:

N_CLASSES = 2
IMG_W = 208  # resize the image, if the input image is too large, training will be very slow.
IMG_H = 208
BATCH_SIZE = 16
CAPACITY = 2000
MAX_STEP = 10000 # with current parameters, it is suggested to use MAX_STEP>10k
learning_rate = 0.0001 # with current parameters, it is suggested to use learning rate<0.0001

logs_train_dir = dataDir + '/logs/recordstrain/'
#    
#    train, train_label = input_data.get_files(train_dir)
tfrecords_file = 'Idcard_train.tfrecords'
train_batch, train_label_batch = read_and_decode(tfrecords_file, batch_size=BATCH_SIZE)
train_batch = tf.cast(train_batch,dtype=tf.float32)
train_label_batch = tf.cast(train_label_batch,dtype=tf.int64)

In [ ]:
N_CLASSES = 2
IMG_W = 208  # resize the image, if the input image is too large, training will be very slow.
IMG_H = 208
BATCH_SIZE = 16
CAPACITY = 2000
MAX_STEP = 10000 # with current parameters, it is suggested to use MAX_STEP>10k
learning_rate = 0.0001 # with current parameters, it is suggested to use learning rate<0.0001

import create_records as cr

def run_training1():
    
    # you need to change the directories to yours.
#    train_dir = '/home/hjxu/PycharmProjects/01_cats_vs_dogs/data/train/'
    logs_train_dir = dataDir + '/logs/recordstrain/'
#    
#    train, train_label = input_data.get_files(train_dir)
    tfrecords_file = 'Idcard_train.tfrecords'
    train_batch, train_label_batch = cr.read_and_decode(tfrecords_file, batch_size=BATCH_SIZE)
    train_batch = tf.cast(train_batch,dtype=tf.float32)
    train_label_batch = tf.cast(train_label_batch,dtype=tf.int64)
    
    train_logits = model.inference(train_batch, BATCH_SIZE, N_CLASSES)
    train_loss = model.losses(train_logits, train_label_batch)        
    train_op = model.trainning(train_loss, learning_rate)
    train__acc = model.evaluation(train_logits, train_label_batch)
       
    summary_op = tf.summary.merge_all()
    sess = tf.Session()
    train_writer = tf.summary.FileWriter(logs_train_dir, sess.graph)
    saver = tf.train.Saver()
    
    sess.run(tf.global_variables_initializer())
    coord = tf.train.Coordinator()
    threads = tf.train.start_queue_runners(sess=sess, coord=coord)
    
    try:
        for step in np.arange(MAX_STEP):
            if coord.should_stop():
                    break
            _, tra_loss, tra_acc = sess.run([train_op, train_loss, train__acc])
               
            if step % 50 == 0:
                print('Step %d, train loss = %.2f, train accuracy = %.2f%%' %(step, tra_loss, tra_acc*100.0))
                summary_str = sess.run(summary_op)
                train_writer.add_summary(summary_str, step)
            
            if step % 2000 == 0 or (step + 1) == MAX_STEP:
                checkpoint_path = os.path.join(logs_train_dir, 'model.ckpt')
                saver.save(sess, checkpoint_path, global_step=step)
                
    except tf.errors.OutOfRangeError:
        print('Done training -- epoch limit reached')
    finally:
        coord.request_stop()
        
    coord.join(threads)
    sess.close()
    
run_training1()
